#ifndef CONSTANTS_H
#define CONSTANTS_H


// parameters of algorithm SA

const double INITIAL_TEMPERATURE = 1000;
const int    NUM_OF_IT_OUTER_MOST_LOOP_WITHOUT_CHANGE = 10;
const int    NUM_OF_IT_INNER_MOST_LOOP_WITHOUT_CHANGE = 1000;
const int    NUM_OF_IT_WITHOUT_CHANGE_TEMPERATUE = 5; // < NUM_OF_IT_INNER_MOST_LOOP_WITHOUT_CHANGE
const int    NUM_OF_THREADS = 1;


#endif // CONSTANTS_H